import './components/gamesList'
import './components/header'
import './components/rock-scissor-spaper'
import './components/header'
import './components/rock-scissor-spaper'
import './components/gues-num'
import './components/rock-scissor-spaper'
import './components/two-digit-calculator'
import './components/header'
import './components/modal-submit'
import './components/dinosaur'
import './components/header'

import './components/dinosaur'